---
title: "hw_5"
author: "Sihyuan Han"
output:
  html_document: default
  pdf_document: default
---

# Baltimore City Crime Data

* 1-1,2
```{r}
library(tidyverse)
library(ggplot2)
bc_crime <-
  read_csv(file = "../R_data/BPD_Part_1_Victim_Based_Crime_Data.csv")
# str(bc_crime)
nrow(bc_crime)
tail(bc_crime)
```

* 1-3
```{r}
bc_crime%>%
  mutate(CrimeDate = parse_date(CrimeDate, format = "%m/%d/%Y"),
         CrimeCode = parse_factor(CrimeCode),
         Description = parse_factor(Description),
         `Inside/Outside` = parse_factor(`Inside/Outside`),
         Weapon = parse_factor(Weapon),
         District = parse_factor(District)) ->
  bc_crime
head(bc_crime)
```

* 1-4
```{r}
bc_crime%>%
  rename(Inside_Outside = `Inside/Outside`,
         Location_1 = `Location 1`,
         Total_Incidents = `Total Incidents`) -> 
  bc_crime

bc_crime%>%
  select(Inside_Outside, Location_1, Total_Incidents)
```

* 1-5
```{r}
# Check duplicated rows
bc_crime%>%
  summarize(dist = nrow(distinct(.)))

nrow(bc_crime)

# How many duplicated rows?
316623-303953

# Remove duplicated rows
bc_crime%>%
  distinct(.keep_all = TRUE) ->
  bc_crime
```

* 1-6
```{r}
bc_crime%>%
  summarize(across(everything(), ~sum(is.na(.))))

# Which columns have the most and least number of values other than NA?
# max: CrimeDate,CrimeCode,Description,Weapon,District,Total_Incidents
# min: Location_1

# remove column with all NA values
bc_crime%>%
  select_if(~any(!is.na(.)))

# Extra Credit
bc_crime%>%
  summarize(across(everything(), ~sum(!is.na(.))))
```

* 1-7
```{r}
# head(sort(unique(bc_crime$Inside_Outside)))

bc_crime%>%
  mutate(
    Inside_Outside = case_when(
      Inside_Outside == "I"  ~"Inside",
      Inside_Outside == "O"  ~"Outside",
      TRUE ~  as.character(Inside_Outside)
    )
  ) ->
  bc_crime
head(bc_crime)
```

* 1-8
```{r}
bc_crime%>%
  separate(CrimeTime,
           into = c("Hour", "Minute", "Second"),
           sep = ":",
           remove = FALSE,
           convert = TRUE) ->
  bc_crime
head(bc_crime)
```

* 1-9
```{r}
bc_crime%>%
  filter(!is.na(Inside_Outside))%>%
  ggplot(aes(y = Hour, fill = Description))+
  geom_bar(width = 1)+
  facet_wrap( ~Inside_Outside)
```

* 1-10
```{r}
bc_crime%>%
  filter(CrimeTime >= parse_time("00:00:00", format = "%H:%M:%S") &
         CrimeTime <= parse_time("04:00:00", format = "%H:%M:%S")) ->
  bc_crime_qten

round(prop.table(table(bc_crime_qten$Total_Incidents, bc_crime_qten$Inside_Outside, useNA = "ifany"), margin = 1),2)
```

* 1-11
```{r}
bc_crime%>%
  saveRDS("../R_output/bc_crime_hw7_output.rds")
```

* Describe the difference in the file sizes: .Rds file is larger than the original file.

* Reload the file you just saved into a variable called balt2 and count the number of rows
```{r}
balt2 <- readRDS("../R_output/bc_crime_hw7_output.rds")
nrow(balt2)
```


## Billboard Data

* 2-1
```{r}
data("billboard")
head(billboard)
```

* 2-2,3,4
```{r}
billboard%>%
  pivot_longer(cols = c(wk1:wk76),
               names_to = "week",
               values_to = "ranking",
               names_prefix = "wk",
               names_transform = list(week = as.numeric),
               values_drop_na = TRUE)%>%
  mutate(date = date.entered+(week-1)*7)%>%
  separate(date.entered,
           into = c("year", "month", "day"),
           sep = "-")%>%
  select(-month, -day)%>%
  arrange(artist, track, week)%>%
  relocate(year)
```

### Iris dataset

* 3-1,2
```{r}
# read_lines("../R_data/iris.names")
iris_data <- read_csv("../R_data/iris.data",
                      col_names = c(
  "sepal_length", "sepal_width", "petal_length", "petal_width", "species"
  )
                      )
head(iris_data)
```

* 3-3
```{r}
iris_data%>%
  pivot_longer(cols = c(sepal_length:petal_width),
               names_to = "name",
               values_to = "value")%>%
  separate(name,
           into = c("plant_part","measure_dim"),
           sep = "_")%>%
  ggplot(aes(species, value))+
  geom_boxplot()+
  facet_grid(plant_part~measure_dim)+
  theme_bw()
```


